-- ================================================================
--  WatchTower — V9 Extend traffic_type CHECK on usage_log
--  Adds UNKNOWN to the allowed values so DPI-classified rows
--  can be written to usage_log alongside the existing types.
-- ================================================================

-- ── 1. DROP old CHECK constraint ────────────────────────────────
-- The constraint name is auto-generated by PostgreSQL from V1.
-- Using IF EXISTS so this is safe to re-run.

ALTER TABLE usage_log
    DROP CONSTRAINT IF EXISTS usage_log_traffic_type_check;


-- ── 2. ADD expanded CHECK constraint ────────────────────────────
-- Now includes UNKNOWN alongside the original 5 + REAL_TRAFFIC.

ALTER TABLE usage_log
    ADD CONSTRAINT usage_log_traffic_type_check
    CHECK (traffic_type IN (
        'STREAMING', 'GAMING', 'VOIP', 'DOWNLOAD',
        'BROWSING', 'UNKNOWN', 'REAL_TRAFFIC'
    ));

-- ── END V9 ──────────────────────────────────────────────────────
